# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'RoamExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'roam-ios',:git => 'https://github.com/roam-ai/roam-ios.git',:tag => '0.0.5'

  # Pods for RoamExample

end
